services:
  - type: web
    name: mailbox-analyser
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: OPENAI_API_KEY
        sync: false  # Set this manually in Render dashboard
      - key: OPENAI_MODEL
        value: gpt-4o-mini
      - key: PORT
        value: 8000
